#!/usr/bin/env bash
set -e
set -x

pushd /tmp
git clone https://github.com/redpanda-data/client-swarm.git

pushd client-swarm
git reset --hard cde2a5e775094dcf15324bd80cf241d0fefc4cd7
cargo build --config 'term.verbose=true' --config 'net.retry=6' --release
cp target/release/client-swarm /usr/local/bin
popd

rm -rf client-swarm
popd
