// Copyright 2025 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package redpanda.core.admin.v2.security.oidc;

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "proto/redpanda/core/pbgen/options.proto";
import "proto/redpanda/core/pbgen/rpc.proto";

option (pbgen.cpp_namespace) = "proto::admin::security::oidc";

service OidcService {
    // GET /v1/security/oidc/whoami
    // Get information about the current authenticated user
    // References:
    // - https://google.aip.dev/136
    rpc OidcWhoAmI(OidcWhoAmIRequest) returns (OidcWhoAmIResponse) {
        option (pbgen.rpc) = {
            authz: USER
        };
    }

    // POST /v1/security/oidc/keys/cache_invalidate
    // Reload the OIDC keys from the identity provider.
    // Flush the JWK cache and force reload keys.
    // References:
    // - https://google.aip.dev/136
    rpc RefreshOidcKeys(RefreshOidcKeysRequest) returns (RefreshOidcKeysResponse) {
        option (pbgen.rpc) = {
            authz: SUPERUSER
        };
    }

    // POST /v1/security/oidc/revoke
    // Reload the keys from the identity provider and disconnect clients.
    // Explicitly revoke client tokens by flushing caches and disconnecting clients to ensure revoked tokens are not used.
    // References:
    // - https://google.aip.dev/136
    rpc RevokeCredentials(RevokeCredentialsRequest) returns (RevokeCredentialsResponse) {
        option (pbgen.rpc) = {
            authz: SUPERUSER
        };
    }
}

// =============================================
/* Resources */
// =============================================

// =============================================
/* RPC Requests and Responses */
// =============================================
// Request message for OidcWhoAmI
// References:
// - https://google.aip.dev/136
message OidcWhoAmIRequest {
    // Empty request
}

// Response message for OidcWhoAmI
// The current authenticated user's information
// References:
// - https://google.aip.dev/136
message OidcWhoAmIResponse {
    // Mapped principal for authorization.
    string id = 1;

    // Unix timestamp of the expiry of the token.
    google.protobuf.Timestamp expire = 2;
}

// Request message for RefreshOidcKeys
// References:
// - https://google.aip.dev/136
message RefreshOidcKeysRequest {
    // Empty request
}

// Response message for RefreshOidcKeys
// References:
// - https://google.aip.dev/136
message RefreshOidcKeysResponse {
    // Empty response
}

// Request message for RevokeCredentials
// References:
// - https://google.aip.dev/136
message RevokeCredentialsRequest {
    // Empty request
}

// Response message for RevokeCredentials
// References:
// - https://google.aip.dev/136
message RevokeCredentialsResponse {
    // Empty response
}

// =============================================
/* Other Messages */
// =============================================